In [ ]:
print("Hello, World!")

Hello, World!


In [ ]:
import numpy as np

In [ ]:
# Array with a single value It is also called list in python
arr = np.array(12)

print(arr)

12


In [ ]:
arr = np.array([12]) # [12] means that it is a 1D array with a single element 12

print(arr)

[12]


In [ ]:
arr3 = np.array([[12]]) # [[12]] means that it is a 2D array with a single element 12

print(arr3, arr3.ndim, arr3.dtype ) # ndim is number of dimensions and dtype is data type of the array

[[12]] 2 int64


In [ ]:
arr4 = np.array([[1,2], [3,4]])

print(arr4, arr4.ndim)

[[1 2]
 [3 4]] 2


In [ ]:
arr4 = np.array([[1,2,3], [3,4,8]])

print(arr4, arr4.ndim, arr4.shape) # shape is the number of rows and columns in the array

[[1 2 3]
 [3 4 8]] 2 (2, 3)


In [ ]:
arr5 = np.array([ [[1,2,3],[4,5,6]]]) # output of shape will be (1,2,3) because it is a 3D array with 1 block, 2 rows and 3 columns

print(arr5, arr5.ndim, arr5.shape) # shape is the number of rows and columns in the array

[[[1 2 3]
  [4 5 6]]] 3 (1, 2, 3)


In [ ]:
arr6 = np.array([[[[[5]]]]])

print(arr6, arr6.ndim)

[[[[[5]]]]] 5


In [ ]:
a = np.eye(5) # eye function creates an identity matrix of given size

print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a = np.eye(5) # eye function creates an identity matrix of given size

print(a, a.dtype) # dtype is data type of the array

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] float64


In [ ]:
b = np.zeros((3,3)) # zeros function creates an array of given shape filled with zeros and is used for null matrix


print(b, b.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [ ]:
c = np.empty((3,2)) # empty function creates an array of given shape filled with random values and is used for uninitialized array

print(c, c.dtype)

[[ 1.79769313e+308 -1.79769313e+308]
 [ 2.00000000e+000  2.22044605e-016]
 [ 2.22507386e-308  4.94065646e-324]] float64


In [ ]:
c = np.empty((2,2)) 
c = c.astype("int32") # astype function is used to change the data type of the array

print(c, c.dtype)

[[0 0]
 [0 0]] int32


In [ ]:
d = np.ones((3,3)) # ones function creates an array of given shape filled with ones and is used for unit matrix

print(d, d.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] float64


In [ ]:
d = np.arange(10) # arange function creates an array of given range and is used for creating a sequence of numbers

print(d, d.dtype)

[0 1 2 3 4 5 6 7 8 9] int64


In [ ]:
d = np.arange(1,10,3) # arange function creates an array of given range and is used for creating a sequence of numbers

print(d, d.dtype)

[1 4 7] int64


In [ ]:
d = np.arange(0,2,5) 
d = d.astype(float) # is used to change the data type of the array to float
print(d, d.dtype)

[0.] float64


In [ ]:
d = np.arange(0,10,2)

d = d.astype(str)

print(d, d.dtype)

['0' '2' '4' '6' '8'] <U21


In [ ]:
e = np.linspace(0,10,30) # linspace function creates an array of given range and number of elements and is used for creating a sequence of numbers with equal intervals
print(e, e.dtype)
e = e.astype("float32")
print(e, e.dtype)

[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ] float64
[ 0.         0.3448276  0.6896552  1.0344827  1.3793104  1.7241379
  2.0689654  2.413793   2.7586207  3.1034484  3.4482758  3.7931035
  4.137931   4.4827585  4.827586   5.172414   5.5172415  5.862069
  6.206897   6.551724   6.8965516  7.2413793  7.586207   7.9310346
  8.275862   8.620689   8.965517   9.310345   9.655172  10.       ] float32


In [ ]:
f = np.array([1234567890, 2143567876, 1234567890], dtype=np.int32) # int32 is used to store large integers and the miximum digits is 10

print(f, f.dtype)

[1234567890 2143567876 1234567890] int32


In [ ]:
g = np.random.rand(3,3) # random function creates an array of given shape filled with random values between 0 and 1

print(g, g.dtype)

[[0.00913421 0.01803062 0.25485944]
 [0.8375286  0.43256174 0.95369788]
 [0.14913109 0.18850515 0.43950935]] float64


In [ ]:
h = np.random.randint(0,50, (3,3)) # randint function creates an array of given shape filled with random integers between given range
# 0 is the lower bound and 50 is the upper bound and (3,3) is the order of the array
print(h, h.dtype)

[[ 8 37 45]
 [31 43  8]
 [49 12 30]] int32


In [ ]:
i = np.random.random((3,3))
print(i, i.dtype)

[[0.58658362 0.10336476 0.40200965]
 [0.84763419 0.22342777 0.83980515]
 [0.80214964 0.40385279 0.8111863 ]] float64


In [ ]:
a = np.array([1,2,3])
b = np.array([6,7,3])

sum = np.add(a,b) # add function is used to add two arrays element-wise
print(sum)

sub = np.subtract(a,b) # subtract function is used to subtract two arrays element-wise
print(sub)

mul = np.multiply(a,b) # multiply function is used to multiply two arrays element-wise
print(mul)

div = np.divide(a,b) # divide function is used to divide two arrays element-wise
print(div)

pow = np.power(a,b) # power function is used to raise the elements of the first array to the power of the elements of the second array element-wise
print(pow)

mod = np.mod(a,b) # mod function is used to find the remainder of the division of two arrays element-wise
print(mod)


[7 9 6]
[-5 -5  0]
[ 6 14  9]
[0.16666667 0.28571429 1.        ]
[  1 128  27]
[1 2 0]


In [ ]:
abc = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.save("abc", abc) # save function is used to save the array to a file in binary format and it is also used for overwriting the existing file

abc2 = np.load("abc.npy") # load function is used to load the array from a file in binary format
print(abc2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Normal distribution is a continuous probability distribution that is symmetric around its mean and is characterized by its mean and standard deviation. It is also known as Gaussian distribution and is commonly used in statistics and machine learning for modeling real-world data.


# Gen AI

In [ ]:
# Markove Chain is a mathematical model that describes a sequence of possible events in which the probability of each event depends only in the state attainedin the previous event.

st = np.array([
    [0.8,0.2],
    [0.4,0.1]
    ])

sp = np.array([1,0])

next_step = np.dot(st, sp)

a =next_step[0]
b =next_step[1]

print(a * 100, b * 100)

80.0 40.0
